### ISSUE TITLE
Problem with Screen View 

### ISSUE THREAD

**Issue by spidverger** [PhonePresenter/PhonePresenter#4] opened 2018-06-23 03:06 UTC
Configuration : Ubuntu 18.04 - OnePlus 6 Android 8.1.0  OxygenOS 5.1.8 - LibreOffice 6.0.3.2.

Screen View enabled. No slide on smartphone. 

Am I doing something wrong?

![capture du 2018-06-22 23-01-15](https://user-images.githubusercontent.com/40510190/41805088-3de0c988-7670-11e8-992a-af463c3a9455.png)
![screenshot_20180622-230256](https://user-images.githubusercontent.com/40510190/41805108-acccc93c-7670-11e8-8022-6f21717c404e.jpg)

**Comment by chromatical** [comment] 2018-06-23 16:09
Screen View works for me on an Ubuntu 18.04 Live USB, so it must be your device.  What browser are you using? (I'm not very familiar with Android)

**Comment by chromatical** [comment] 2018-07-05 23:49
@spidverger Are you still having this problem?  I am not able to reproduce it.

**Comment by chromatical** [comment] 2018-07-19 22:35
I am closing this issue, as I cannot reproduce it.  Feel free to comment with more information and I will reopen it.

**Closed as completed by chromatical** 2018-07-19 22:35 UTC
Labels: more info needed
